export default [
    {
      path: '/',
      component: '../layouts/BlankLayout',

      routes: [
        {
          path: '/',
          component: '../layouts/BlankLayout',

          routes: [
            // {
            //   path: '/portal',
            //   component: './web-portals',
            // },
            {
              path: '/user',
              component: '../layouts/UserLayout',
              routes: [
                {
                  path: '/user',
                  redirect: '/user/login',
                },
                {
                  name: 'login',
                  path: '/user/login',
                  component: './user/login',
                },
                {
                  name: 'register-result',
                  path: '/user/register-result',
                  component: './user/register-result',
                },
                {
                  name: 'register',
                  path: '/user/register',
                  component: './user/register',
                },
                {
                  component: '404',
                },
              ],
            },
            {
              path: '/passage',
              component: './web-passage',
            },
            {
              path: '/',
              component: '../layouts/BasicLayout',
              wrappers: ['@/pages/Authorized'],
              routes: [
                {
                  path: '/',
                  redirect: '/dist', // 页面从定向
                },
                {
                  path: '/dist',
                  name: '首页',
                  icon: 'home',
                  component: './home',
                },
                {
                  path: '/timeLimit/detail',
                  name: '项目时间限制',
                  icon: 'home',
                  component: './management/second/time-check',
                  hideInMenu: true,
                },
                {
                  path: '/openProjects/detail',
                  name: '详情',
                  icon: 'home',
                  component: './common/detail',
                  hideInMenu: true,
                },
                {
                  path: '/announcement/detail',
                  name: '公告详情',
                  icon: 'home',
                  component: './settings/announcement/detail',
                  hideInMenu: true,
                },
                // {
                //   path: '/tproject',
                //   name: '项目管理',
                //   icon: 'project',
                //   authority:[3],
                //   routes: [
                {
                  name: '项目拟题',
                  path: '/tproject/apply',
                  component: './project-t/apply',
                  authority: [3],
                  icon: 'file-add',
                },
                {
                  name: '修改立项申请表',
                  path: '/tproject/manage/edit',
                  component: './project-t/edit',
                  hideInMenu: true,
                  authority: [3],
                  icon: 'file-add',
                },
                {
                  name: '项目详情',
                  path: '/tproject/manage/detail',
                  component: './common/detail',
                  authority: [3],
                  hideInMenu: true,
                  icon: 'file-add',
                },
                {
                  name: '重点项目申请',
                  path: '/tproject/manage/key-detail',
                  component: './common/key-detail',
                  authority: [3],
                  hideInMenu: true,
                  icon: 'file-add',
                },
                {
                  name: '已报项目',
                  path: '/tproject/manage',
                  component: './project-t/projects',
                  authority: [3],
                  icon: 'file-done',
                },
                {
                  name: '中期成员变更',
                  path: '/tproject/manage/mid-memberchange',
                  component: './project-t/midmemberchange',
                  authority: [3],
                  icon: 'file-done',
                  hideInMenu: true,
                },
                {
                  name: '拟题审批',
                  path: '/tproject/manage/key-project',
                  component: './project-t/key-projects',
                  authority: [3],
                  icon: 'file-done',
                  hideInMenu: true,
                },
                {
                  name: '成员审批',
                  path: '/tproject/members',
                  component: './project-t/members',
                  authority: [3],
                  icon: 'usergroup-add',
                },
                //   ],
                // },
                // {
                //   path: '/sproject',
                //   name: '项目管理',
                //   icon: 'project',
                //   authority:[1,2],
                //   routes: [
                {
                  name: '项目申请',
                  path: '/sproject/join/all',
                  component: './project-s/join/projects',
                  authority: [1, 2],
                  icon: 'file-add',
                },
                {
                  name: '证书申领',
                  path: '/certificate/stu',
                  component: './certificate/stu-certificate',
                  authority: [1, 2],
                  icon: 'file-add',
                },
                {
                  name: '项目申请表',
                  path: '/sproject/join/all/apply',
                  component: './project-s/join/basic-form',
                  authority: [1, 2],
                  icon: 'file-add',
                  hideInMenu: true,
                },
                {
                  name: '已选项目',
                  path: '/sproject/manage',
                  component: './project-s/manage/projects',
                  authority: [1, 2],
                  icon: 'file-done',
                },
                {
                  name: '项目结题',
                  path: '/sproject/manage/overproject',
                  component: './project-s/manage/overproject',
                  authority: [1, 2],
                  icon: 'file-done',
                  hideInMenu: true,
                },
                {
                  name: '重点项目申请',
                  path: '/sproject/manage/keyProject',
                  component: './project-s/manage/key-project',
                  authority: [1, 2],
                  icon: 'file-add',
                  hideInMenu: true,
                },
                {
                  name: '重点项目申请',
                  path: '/sproject/manage/key-detail',
                  component: './common/key-detail',
                  authority: [1, 2],
                  icon: 'file-add',
                  hideInMenu: true,
                },
                {
                  name: '中期成员变更',
                  path: '/sproject/manage/mid-memberchange',
                  component: './project-s/manage/midmemberchange',
                  authority: [1, 2],
                  icon: 'file-add',
                  hideInMenu: true,
                },
                {
                  name: '项目详情',
                  path: '/sproject/join/all/detail',
                  component: './common/detail',
                  // authority: [1, 2],
                  hideInMenu: true,
                  icon: 'file-add',
                },
                {
                  name: '项目详情',
                  path: '/sproject/manage/detail',
                  component: './common/detail',
                  // authority: [1, 2],
                  hideInMenu: true,
                  icon: 'file-add',
                },
                // {
                //   name: '证书申领',
                //   path: '/sproject/certificate',
                //   component: './project-s/certificate',
                //   authority:[1,2],
                //   icon: 'read'
                // },
                //   ],
                // },
                // {
                //   path: '/project/auth',
                //   name: '项目审批',
                //   icon: 'diff',
                //   routes: [
                {
                  name: '实验中心审批',
                  path: '/auth/lab',
                  authority: [4],
                  routes: [
                    {
                      name: '拟题审批',
                      path: '/auth/lab/pre-project',
                      component: './management/lab/pre-projects',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目立项审批',
                      path: '/auth/lab/project',
                      component: './management/lab/projects',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目立项审批',
                      path: '/auth/lab/key-project',
                      component: './management/lab/key-projects',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目结题审批',
                      path: '/auth/lab/conclusionCheck',
                      component: './management/lab/conclusionCheck',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目结题退回复核',
                      path: '/auth/lab/compound',
                      component: './management/lab/compound',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目结题审批',
                      path: '/auth/lab/keyconclusionCheck',
                      component: './management/lab/keyconclusionCheck',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目结题退回复核',
                      path: '/auth/lab/keycompound',
                      component: './management/lab/keycompound',
                      icon: 'solution',
                    },
                    // {
                    //   name: '重点项目结题审批',
                    //   path: '/auth/lab/conclusionCheck',
                    //   component: './management/lab/projects',
                    //   icon: 'solution',
                    // },
                    {
                      name: '项目详情',
                      path: '/auth/lab/project/detail',
                      component: './common/detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '项目详情',
                      path: '/auth/lab/pre-project/detail',
                      component: './common/detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目详情',
                      path: '/auth/lab/key-project/detail',
                      component: './common/key-detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'experiment',
                },
                {
                  name: '时限设置',
                  authority: [4],
                  path: '/auth/second/settings',
                  component: './management/second/settings',
                  icon: 'setting',
                },
                // {
                //   name: '查看本院历史所有',
                //   authority: [4],
                //   path: '/auth/search/collegehistory',
                //   component: './management/lab/history',
                //   icon: 'HistoryOutlined ',
                // },
                {
                  name: '二级单位审批',
                  path: '/auth/second',
                  authority: [5],
                  routes: [
                    {
                      name: '普通项目结题审批',
                      path: '/auth/second/porject',
                      component: './overwaitmark/porject',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目结题审批',
                      path: '/auth/second/k-porject',
                      component: './overwaitmark/k-porject',
                      icon: 'solution',
                    },
                    // {
                    //   name: '普通项目结题退回复核',
                    //   path: '/auth/second/return-project',
                    //   component: './overwaitmark/project-return',
                    //   icon: 'solution',
                    // },
                    // {
                    //   name: '重点项目结题退回复核',
                    //   path: '/auth/second/return-keyproject',
                    //   component: './overwaitmark/keyproject-return',
                    //   icon: 'solution',
                    // },
                    {
                      name: '普通项目立项审批',
                      path: '/auth/second/project',
                      component: './management/second/projects',
                      icon: 'solution',
                    },

                    {
                      name: '重点项目立项审批',
                      path: '/auth/second/key-project',
                      component: './management/second/key-projects',
                      icon: 'solution',
                    },
                    {
                      name: '项目详情',
                      path: '/auth/second/project/detail',
                      component: './common/detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目详情',
                      path: '/auth/second/key-project/detail',
                      component: './common/key-detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'team',
                },
                // {
                //   name:'test',
                //   path:'test',
                //   component:'./common/test'
                // },
                {
                  name: '项目查询',
                  path: '/auth/select',
                  authority: [6, 7],
                  icon: 'solution',
                  routes: [
                    {
                      name: '查询',
                      path: '/auth/select/project',
                      component: './management/select/key-project',
                      icon: 'solution',
                    },
                  ],
                },
                {
                  name: '职能部门审批',
                  path: 'auth/equipment',
                  authority: [6, 7],
                  routes: [
                    {
                      name: '普通项目审批',
                      path: '/auth/equipment/project',
                      component: './management/equipment/projects',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目审批',
                      path: '/auth/equipment/key-project',
                      component: './management/equipment/key-projects',
                      icon: 'solution',
                    },
                    {
                      name: '项目详情',
                      path: '/auth/equipment/project/detail',
                      component: './common/detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目详情',
                      path: '/auth/equipment/key-project/detail',
                      component: './common/key-detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'reconciliation',
                },
                //   ],
                // },

                {
                  path: '/midtermcheck',
                  name: '中期项目管理',
                  routes: [
                    {
                      name: '普通项目审批',
                      path: '/midtermcheck/project',
                      component: './midtermcheck',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目审批',
                      path: '/midtermcheck/key-project',
                      component: './midtermcheck/project',
                      icon: 'solution',
                    },
                    {
                      name: '普通退回项目复核',
                      path: '/midtermcheck/return-project',
                      component: './midtermcheck/hitproject',
                      icon: 'solution',
                    },
                    {
                      name: '重点退回项目复核',
                      path: '/midtermcheck/return-keyproject',
                      component: './midtermcheck/hitkeyproject',
                      icon: 'solution',
                    },
                    {
                      name: '成员变更审核',
                      path: '/midtermcheck/memberchangecheck',
                      component: './midtermcheck/memberchangecheck',
                      icon: 'solution',
                    },
                    {
                      name: '项目详情',
                      path: '/midtermcheck/project/detail',
                      component: './common/detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目详情',
                      path: '/midtermcheck/key-project/detail',
                      component: './common/key-detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'solution',
                  authority: [6, 7],
                },
                {
                  name: '结题总览',
                  path: '/overall',
                  routes: [
                    {
                      name: '普通项目学院结题已通过',
                      path: '/overall/college',
                      component: './overwaitmark/college',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目学院项目详情',
                      path: '/overall/college/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '普通项目职能部门结题已通过',
                      path: '/overall/function',
                      component: './overwaitmark/function',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目部门项目详情',
                      path: '/overall/function/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目学院结题已通过',
                      path: '/overall/keycollege',
                      component: './overwaitmark/keycollege',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目学院项目详情',
                      path: '/overall/keycollege/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目职能部门结题已通过',
                      path: '/overall/keyfunction',
                      component: './overwaitmark/keyfunction',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目职能部门项目详情',
                      path: '/overall/keyfunction/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'safety-certificate',
                  authority: [4, 5, 9],
                },
                {
                  name: '结题总览',
                  path: '/overfunctionall',
                  routes: [
                    {
                      name: '已结题重点项目',
                      path: '/overfunctionall/key',
                      component: './overall/key',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目详情',
                      path: '/overfunctionall/key/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '已结题普通项目',
                      path: '/overfunctionall/normal',
                      component: './overall/normal',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目详情',
                      path: '/overfunctionall/normal/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'safety-certificate',
                  authority: [6],
                },
                {
                  path: '/overcheck',
                  name: '结题项目管理',
                  routes: [
                    {
                      name: '普通项目审批',
                      path: '/overcheck/project',
                      component: './overcheck/project',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目审批',
                      path: '/overcheck/key-project',
                      component: './overcheck/keyproject',
                      icon: 'solution',
                    },
                    // {
                    //   name: '普通退回项目复核',
                    //   path: '/overcheck/return-project',
                    //   component: './overcheck/project-return',
                    //   icon: 'solution',
                    // },
                    // {
                    //   name: '重点退回项目复核',
                    //   path: '/overcheck/return-keyproject',
                    //   component: './overcheck/keyproject-return',
                    //   icon: 'solution',
                    // },
                    {
                      name: '普通项目详情',
                      path: '/overcheck/project/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目详情',
                      path: '/overcheck/key-project/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'solution',
                  authority: [9],
                },
                {
                  path: '/overcheckfunction',
                  name: '结题项目管理',
                  routes: [
                    {
                      name: '普通项目审批',
                      path: '/overcheckfunction/project',
                      component: './overcheck/project-f',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目审批',
                      path: '/overcheckfunction/keyproject',
                      component: './overcheck/keyproject-f',
                      icon: 'solution',
                    },
                    {
                      name: '普通退回项目复核',
                      path: '/overcheckfunction/return-project',
                      component: './overcheck/project-f-return',
                      icon: 'solution',
                    },
                    {
                      name: '重点退回项目复核',
                      path: '/overcheckfunction/return-keyproject',
                      component: './overcheck/keyproject-f-return',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目详情',
                      path: '/overcheckfunction/project/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                    {
                      name: '重点项目详情',
                      path: '/overcheckfunction/keyproject/detail',
                      component: './project-s/manage/overproject',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'solution',
                  authority: [6],
                },
                {
                  name: '内定项目管理',
                  path: '/inner',
                  authority: [6, 7],
                  routes: [
                    {
                      name: '内定项目申请',
                      path: '/inner/project',
                      component: './innerproject/normal',
                      icon: 'solution',
                    },
                    {
                      name: '已申请项目',
                      path: '/inner/all',
                      component: './innerproject/readyproject',
                      icon: 'solution',
                    },
                    {
                      name: '成员管理',
                      path: '/inner/member',
                      component: './innerproject/member',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目详情',
                      path: '/inner/all/detail',
                      component: './common/key-detail',
                      hideInMenu: true,
                      icon: 'team',
                    },
                  ],
                  icon: 'reconciliation',
                },
                {
                  path: '/funds',
                  name: '资金管理',
                  component: './funds',
                  icon: 'account-book',
                  authority: [6, 7],
                },
                {
                  path: '/achievement',
                  name: '成果统计',
                  component: './achievement',
                  icon: 'bar-chart',
                  authority: [6, 7],
                },
                {
                  path: '/certificate/tec',
                  name: '证书管理',
                  component: './certificate/tec-certificate',
                  icon: 'file-add',
                  authority: [6, 7],
                },
                {
                  path: '/approval',
                  name: '立项评审',
                  icon: 'solution',
                  routes: [
                    {
                      name: '普通项目立项审批',
                      path: '/approval/project',
                      component: './approval/project',
                      icon: 'solution',
                    },
                    {
                      name: '普通项目待审批详情',
                      path: '/approval/project/detail',
                      component: './common/detail',
                      hideInMenu: true,
                      icon: 'file-add',
                    },
                    {
                      name: '重点项目立项审批',
                      path: '/approval/keyproject',
                      component: './approval/key-project',
                      icon: 'solution',
                    },
                    {
                      name: '重点项目立项审批详情',
                      path: '/approval/keyproject/detail',
                      component: './common/key-detail',
                      hideInMenu: true,
                      icon: 'file-add',
                    },
                    // {
                    //   name: '普通项目详情',
                    //   path: '/overcheckfunction/project/detail',
                    //   component: './project-s/manage/overproject',
                    //   hideInMenu: true,
                    //   icon: 'team',
                    // },
                    // {
                    //   name: '重点项目详情',
                    //   path: '/overcheckfunction/keyproject/detail',
                    //   component: './project-s/manage/overproject',
                    //   hideInMenu: true,
                    //   icon: 'team',
                    // },
                  ],
                  authority: [11],
                },
                {
                  path: '/selfInformation/edit',
                  name: '完善个人信息',
                  component: './user-information',
                  hideInMenu: true,
                  icon: 'user',
                },
                {
                  path: '/account/message',
                  name: '消息中心',
                  component: './message',
                  hideInMenu: true,
                  icon: 'message',
                },
                // {
                //   path: '/settings',
                //   name: '系统设置',
                //   icon: 'setting',
                //   authority:[5,6,7],
                //   routes: [
                {
                  name: '设置',
                  path: '/settings-s',
                  routes: [
                    {
                      name: '基本设置',
                      path: '/settings-s/basic',
                      component: './settings/basic',
                      icon: 'solution',
                    },
                    {
                      name: '立项审批设置',
                      path: '/settings-s/approval-c',
                      component: './settings/approval-c',
                      icon: 'solution',
                    },
                    {
                      name: '需结题审核人学院设置',
                      path: '/settings-s/reviewer',
                      component: './settings/reviewer',
                      icon: 'solution',
                    },
                    {
                      name: '结题等级比例设置',
                      path: '/settings-s/grade',
                      component: './settings/grade',
                      icon: 'solution',
                    },
                  ],
                  icon: 'profile',
                  authority: [6, 7],
                },
                {
                  name: '权限设置',
                  path: '/settings/authority',
                  component: './settings/authority',
                  icon: 'safety-certificate',
                  authority: [6, 7],
                },
                {
                  name: '站内公告管理',
                  path: '/settings/announcement',
                  component: './settings/announcement/announcements',
                  icon: 'file-text',
                  authority: [4, 6, 7],
                },
                {
                  name: '门户网站管理',
                  path: '/settings/web-announcement',
                  component: './settings/web-announcement/announcements',
                  icon: 'file-text',
                  authority: [6],
                },
                {
                  name: '新增公告',
                  path: '/settings/web-announcement/append',
                  component: './settings/web-announcement/append',
                  icon: 'file-text',
                  hideInMenu: true,
                  authority: [6],
                },
                {
                  name: '新增项目',
                  path: '/settings/web-announcement/append-project',
                  component: './settings/web-announcement/appendProject',
                  icon: 'file-text',
                  hideInMenu: true,
                  authority: [6],
                },
                {
                  name: '新增公告',
                  path: '/settings/announcement/append',
                  component: './settings/announcement/append',
                  icon: 'file-text',
                  hideInMenu: true,
                  authority: [4, 6, 7],
                },
                {
                  name: '公告详情',
                  path: '/settings/announcement/detail',
                  component: './settings/announcement/detail',
                  icon: 'file-text',
                  hideInMenu: true,
                  authority: [4, 6, 7],
                },
                {
                  name: '结题及立项评审人设置',
                  path: '/settings/college-a',
                  component: './settings/college-a',
                  icon: 'file-text',
                  authority: [4],
                },
                //   ],
                // },
                // {
                //   path: '/dashboard',
                //   name: 'dashboard',
                //   icon: 'dashboard',
                //   routes: [
                //     {
                //       name: 'analysis',
                //       path: '/dashboard/analysis',
                //       component: './dashboard/analysis',
                //     },
                //     {
                //       name: 'monitor',
                //       path: '/dashboard/monitor',
                //       component: './dashboard/monitor',
                //     },
                //     {
                //       name: 'workplace',
                //       path: '/dashboard/workplace',
                //       component: './dashboard/workplace',
                //     },
                //   ],
                // },
                // {
                //   path: '/form',
                //   icon: 'form',
                //   name: 'form',
                //   routes: [
                //     {
                //       name: 'basic-form',
                //       path: '/form/basic-form',
                //       component: './form/basic-form',
                //     },
                //     {
                //       name: 'step-form',
                //       path: '/form/step-form',
                //       component: './form/step-form',
                //     },
                //     {
                //       name: 'advanced-form',
                //       path: '/form/advanced-form',
                //       component: './form/advanced-form',
                //     },
                //   ],
                // },
                // {
                //   path: '/list',
                //   icon: 'table',
                //   name: 'list',
                //   routes: [
                //     {
                //       path: '/list/search',
                //       name: 'search-list',
                //       component: './list/search',
                //       routes: [
                //         {
                //           path: '/list/search',
                //           redirect: '/list/search/articles',
                //         },
                //         {
                //           name: 'articles',
                //           path: '/list/search/articles',
                //           component: './list/search/articles',
                //         },
                //         {
                //           name: 'project',
                //           path: '/list/search/project',
                //           component: './list/search/project',
                //         },
                //         {
                //           name: 'applications',
                //           path: '/list/search/applications',
                //           component: './list/search/applications',
                //         },
                //       ],
                //     },
                //     {
                //       name: 'table-list',
                //       path: '/list/table-list',
                //       component: './list/table-list',
                //     },
                //     {
                //       name: 'basic-list',
                //       path: '/list/basic-list',
                //       component: './list/basic-list',
                //     },
                //     {
                //       name: 'card-list',
                //       path: '/list/card-list',
                //       component: './list/card-list',
                //     },
                //   ],
                // },
                // {
                //   path: '/profile',
                //   name: 'profile',
                //   icon: 'profile',
                //   routes: [
                //     {
                //       name: 'basic',
                //       path: '/profile/basic',
                //       component: './profile/basic',
                //     },
                //     {
                //       name: 'advanced',
                //       path: '/profile/advanced',
                //       component: './profile/advanced',
                //     },
                //   ],
                // },
                // {
                //   name: 'result',
                //   icon: 'check-circle-o',
                //   path: '/result',
                //   routes: [
                //     {
                //       name: 'success',
                //       path: '/result/success',
                //       component: './result/success',
                //     },
                //     {
                //       name: 'fail',
                //       path: '/result/fail',
                //       component: './result/fail',
                //     },
                //   ],
                // },
                // {
                //   name: 'exception',
                //   icon: 'warning',
                //   path: '/exception',
                //   routes: [
                //     {
                //       name: '403',
                //       path: '/exception/403',
                //       component: './exception/403',
                //     },
                //     {
                //       name: '404',
                //       path: '/exception/404',
                //       component: './exception/404',
                //     },
                //     {
                //       name: '500',
                //       path: '/exception/500',
                //       component: './exception/500',
                //     },
                //   ],
                // },
                // {
                //   name: 'account',
                //   icon: 'user',
                //   path: '/account',
                //   routes: [
                //     {
                //       name: 'center',
                //       path: '/account/center',
                //       component: './account/center',
                //     },
                //     {
                //       name: 'settings',
                //       path: '/account/settings',
                //       component: './account/settings',
                //     },
                //   ],
                // },
                // {
                //   name: 'editor',
                //   icon: 'highlight',
                //   path: '/editor',
                //   routes: [
                //     {
                //       name: 'flow',
                //       path: '/editor/flow',
                //       component: './editor/flow',
                //     },
                //     {
                //       name: 'mind',
                //       path: '/editor/mind',
                //       component: './editor/mind',
                //     },
                //     {
                //       name: 'koni',
                //       path: '/editor/koni',
                //       component: './editor/koni',
                //     },
                //   ],
                // },
                {
                  path: '/',
                  redirect: '/dashboard/analysis',
                },
                {
                  component: '404',
                },
              ],
            },
          ],
        },
      ],
    },
  ]